services:
  gps_server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - gps_data:/usr/src/app/data
    environment:
      - NODE_ENV=production

volumes:
  gps_data: