version: '2'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=your_secure_password
      - DB_NAME=gps_tracking
      - CORS_ORIGIN=*
      - RATE_LIMIT_WINDOW=15
      - RATE_LIMIT_MAX=100
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - gps-network

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=your_secure_password
      - MYSQL_DATABASE=gps_tracking
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - gps-network

volumes:
  mysql-data:

networks:
  gps-network:
    driver: bridge 