CREATE TABLE `Users` (
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
	`username` VARCHAR(255) NOT NULL UNIQUE,
	`email` VARCHAR(255) NOT NULL UNIQUE,
	`password` VARCHAR(255) NOT NULL,
	`is_verified` BOOLEAN NOT NULL DEFAULT 0,
	`verification_code` VARCHAR(10),
	`verification_expires` TIMESTAMP,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`pending_email` VARCHAR(255) DEFAULT NULL,
	`provider` VARCHAR(50) DEFAULT 'local',
	`provider_id` VARCHAR(255),
	`provider_data` TEXT,
	PRIMARY KEY(`id`)
);


CREATE TABLE `Locations` (
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
	`longtitude` DECIMAL(10,6) NOT NULL,
	`latitude` DECIMAL(10,6) NOT NULL,
	`timestamp` TIMESTAMP NOT NULL,
	`accuracy` DECIMAL(5,2),
	`speed` DECIMAL(5,2),
	`altitude` DECIMAL(7,2),
	`satelites` TINYINT,
	`device_id` INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE INDEX `Locations_index_0`
ON `Locations` (`timestamp`);
CREATE TABLE `Devices` (
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
	`device_id` VARCHAR(10) NOT NULL UNIQUE,
	`name` VARCHAR(255),
	`status` VARCHAR(50) NOT NULL DEFAULT 'active',
	`last_seen` TIMESTAMP,
	`interval_gps` INTEGER UNSIGNED NOT NULL DEFAULT 60,
	`interval_send` INTEGER UNSIGNED NOT NULL DEFAULT 1,
	`geofence` JSON,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`user_id` INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE INDEX `Devices_index_0`
ON `Devices` (`device_id`, `status`);
CREATE TABLE `Alerts` (
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
	`type` VARCHAR(255) NOT NULL,
	`message` MEDIUMTEXT(65535) NOT NULL,
	`is_read` BOOLEAN NOT NULL DEFAULT FALSE,
	`created_at` TIMESTAMP NOT NULL,
	`device_id` INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY(`id`)
);


ALTER TABLE `Users`
ADD FOREIGN KEY(`id`) REFERENCES `Devices`(`user_id`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `Devices`
ADD FOREIGN KEY(`id`) REFERENCES `Locations`(`device_id`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `Devices`
ADD FOREIGN KEY(`id`) REFERENCES `Alerts`(`device_id`)
ON UPDATE NO ACTION ON DELETE CASCADE;